apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vinted-deploy
  name: vinted-deploy
spec:
  ports:
  - port: 4242
    protocol: TCP
    targetPort: 3000
  selector:
    app: vinted-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
