{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vinted.serviceAccountName" . }}
  labels:
{{ include "vinted.labels" . | indent 4 }}
{{- end -}}
